# -*- coding: utf-8 -*-
"""Advanced Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qlUzCeNeRRoyJsAq_hp_yTIMcsQqZ0E0

# Practice for the advanced syntax for python

#String
"""

name = "Kyle Wu"
GPA = "4.0"
words = f"My name is {name} with GPA of {GPA}"

"""#Tuple

##Function
"""

def sum_and_product(x,y):
  return x+y, x*y

s,p = sum_and_product(3,4)

"""## Args and Kwargs (Used for multiple input )

"""

def magic(*args, **kwargs):
  print("unnamed args:",args) #所有沒 naming 的 arguments 會被放在這
  print("keyword args:", kwargs) #所有有 naming 的 arguments 以 dictionary 存在這

magic(1,2,key = "word", key2 = "word2")

"""#Type Labeling"""

my_list = [1,2,3]

def total(xs: list) -> float:
  return sum(xs)

print(total(my_list))

"""##Testing / Assertion"""

a = 10
b = 6
assert a+b == 15, "a+b should = 15"